/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fhrfjukpubzcwatveaqk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZocmZqdWtwdWJ6Y3dhdHZlYXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MDM0MzAsImV4cCI6MjA4NzI3OTQzMH0.70xZIAl-ticm9g4-KwCTVFDapTF1PRluFLc_3JWK4-8"